project:
  type: website
  output-dir: docs

website:
  title: "Neva Morgan | Daily Assignment 22"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    self-contained: true

editor: visual

